version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: monitoring
      POSTGRES_PASSWORD: monitoring123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  server:
    build: ./server
    environment:
      DATABASE_URL: postgres://monitoring:monitoring123@postgres:5432/monitoring?sslmode=disable
      API_PORT: 8080
      JWT_SECRET: your-secret-key-here
    depends_on:
      - postgres
    restart: unless-stopped

  app:
    build: ./app
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
      - app
    restart: unless-stopped

volumes:
  postgres_data: 